name: Delete old JAR snapshots

on:
  workflow_dispatch:
    inputs:
      min-versions-to-keep:
        description: 'Minimum number of versions to keep'
        required: true
        default: 1
  schedule:
    - cron: '0 0 */3 * *'

concurrency:
  group: besom-gh-packages
  cancel-in-progress: false

jobs:
  delete-old-jars:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        package-name:
          - 'org.virtuslab.besom-json_3'
          - 'com.virtuslab.besom-core_3'
          - 'com.virtuslab.besom-cats_3'
          - 'com.virtuslab.besom-zio_3'
          - 'org.virtuslab.besom-codegen_3'
          - 'org.virtuslab.besom-compiler-plugin_3'
          - 'com.virtuslab.besom-aws_3'
          - 'com.virtuslab.besom-azure_3'
          - 'com.virtuslab.besom-docker_3'
          - 'com.virtuslab.besom-eks_3'
          - 'com.virtuslab.besom-gcp_3'
          - 'com.virtuslab.besom-kubernetes_3'
          - 'com.virtuslab.besom-random_3'
          - 'com.virtuslab.besom-tls_3'
    steps:
      - uses: actions/delete-package-versions@v5.0.0
        continue-on-error: true
        with:
          min-versions-to-keep: ${{ github.event.inputs.min-versions-to-keep || 1 }}
          delete-only-pre-release-versions: true
          package-name: ${{ matrix.package-name }}
          package-type: 'maven'
