name: Publish Besom providers to GitHub Packages

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: gh-packages
  cancel-in-progress: false

jobs:
  publish-provider:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        provider:
          - aws
          - azure
          - docker
          - gcp
          - kubernetes
          - random
          - tls
    steps:
      - uses: VirtusLab/besom/.github/workflows/publish-provider.yaml@develop
        with:
          provider: ${{ matrix.provider }}
