name: Publish Besom language plugin to GitHub Packages

on:
  workflow_dispatch:

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

concurrency:
  group: gh-packages
  cancel-in-progress: false

jobs:
  publish-lang:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4
      - uses: extractions/setup-just@v1
        with:
          just-version: '1.14.0' # just for sanity
      - uses: coursier/cache-action@v6.4.3
      - uses: VirtusLab/scala-cli-setup@v1.1.0
        with:
          jvm: graalvm-java11:22.3.1
          power: true
      - uses: actions/setup-go@v4
        with:
          go-version: '1.20'
      - name: Upsert GitHub release
        run: |-
          just upsert-gh-release
      - name: Publish language plugins
        run: |-
          just publish-language-plugins-all
